
# Handwritten Digit Recognition

## Dataset Overview

The project utilizes the Digit MNIST dataset, which consists of more than 60,000 training images and 10,000 testing images. Each image represents a handwritten digit from 0 to 9.

For this implementation, 12,000 images have been extracted from the MNIST dataset for training and testing purposes. The dataset contains 10 different classes representing the digits 0-9.

## Model Architecture

The Handwritten Digit Recognition Model has been implemented using a Neural Network with the following layers:

- **Input Layer**: Accepts the pixel values of the images.
- **Hidden Layers**:
  - ReLU (Rectified Linear Unit) for activation.
- **Output Layer**:
  - Softmax for classifying digits into 10 categories.

## Implementation Details

- The model is trained using TensorFlow/Keras.
- The dataset is preprocessed by normalizing pixel values.
- The model's performance is evaluated using accuracy metrics.

## Usage Instructions

1. Load the dataset using `digit_mnist.load_data()`.
2. Preprocess the data by reshaping and normalizing it.
3. Define and compile the neural network model.
4. Train the model using the training dataset.
5. Evaluate the model using the test dataset.

## Results

The model achieves high accuracy in recognizing handwritten digits. Performance can be improved by tuning hyperparameters, increasing training epochs, or using convolutional neural networks (CNNs).

## Future Improvements

- Implementing CNNs for better accuracy.
- Exploring data augmentation techniques.
- Using transfer learning for improved performance.


In [ ]:
!pip install tensorflow
import tensorflow as tf

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical
import warnings
from sklearn.metrics import classification_report, confusion_matrix

In [4]:
warnings.filterwarnings('ignore')

In [23]:
digit_mnist = tf.keras.datasets.mnist
(X_train,y_train) , (X_test,y_test) = digit_mnist.load_data()

In [24]:
X_train= X_train.astype('float32')/ 255
X_test = X_test.astype('float32')/255

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

In [25]:
model = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(128, activation='relu'),
    Dense(256, activation='relu'),
    Dense(10, activation='softmax')
])


In [26]:
opti = tf.keras.optimizers.Adam(learning_rate=0.001)

In [27]:
model.compile(
    optimizer=opti,
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [28]:
model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test)
)

Epoch 1/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8847 - loss: 0.3935 - val_accuracy: 0.9679 - val_loss: 0.1013
Epoch 2/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9689 - loss: 0.0959 - val_accuracy: 0.9725 - val_loss: 0.0854
Epoch 3/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9797 - loss: 0.0617 - val_accuracy: 0.9744 - val_loss: 0.0827
Epoch 4/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9852 - loss: 0.0452 - val_accuracy: 0.9794 - val_loss: 0.0754
Epoch 5/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9883 - loss: 0.0354 - val_accuracy: 0.9751 - val_loss: 0.0907
Epoch 6/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9906 - loss: 0.0288 - val_accuracy: 0.9792 - val_loss: 0.0851
Epoch 7/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9926 - loss: 0.0237 - val_accuracy: 0.9803 - val_loss: 0.0771
Epoch 8/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.9935 - loss: 0.0196 -

In [29]:
y_prob=model.predict(X_test)

y_pred = np.argmax(y_prob, axis=1)

if y_test.ndim > 1 and y_test.shape[1] > 1:
    y_test = np.argmax(y_test, axis=1)

print(confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
[[ 974    0    3    0    1    2    4    1    3    2]
 [   0 1125    3    0    1    0    2    3    0    2]
 [   0    0 1000    0    2    0    1    5    1    0]
 [   1    2   11 1004    0    7    1    1   11    3]
 [   0    0    2    0  951    1    3    0    1    6]
 [   0    1    0    1    1  875    7    0    5    1]
 [   2    0    0    0    3    2  939    0    0    0]
 [   0    1    3    3    0    2    0 1008    3    1]
 [   2    6   10    1    2    2    1    2  946    1]
 [   1    0    0    1   21    1    0    8    4  993]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       990
           1       0.99      0.99      0.99      1136
           2       0.97      0.99      0.98      1009
           3       0.99      0.96      0.98      1041
           4       0.97      0.99      0.98       964
           5       0.98      0.98      0.98       891
           6       0.98      0.99      0.99      